// Generated by CoffeeScript 1.8.0
var async, bloodyTrail, zombie, zombieSeed;

console.log('\nRunning Zombie\n');

async = require('async');

zombieSeed = require('zombie');

zombie = new zombieSeed();

bloodyTrail = [
  function(step) {
    var onTheRun;
    console.log('Going towards smell\n');
    onTheRun = Date.now();
    return zombie.visit('http://www.yadaim2.co.il/index.asp', function(err) {
      if (err) {
        return step(err);
      } else {
        return step(null, zombie.document, onTheRun);
      }
    });
  }, function(doc, onTheRun, step) {
    var rot, rotHTML;
    console.log('\nArrived at ' + (Date.now() - onTheRun) / 1000 + 'sec\n');
    rot = doc.querySelectorAll('#fb-root');
    rotHTML = rot[0].outerHTML;
    return step(null, rotHTML);
  }, function(results, step) {
    console.log('Eating.\n');
    return step(null, results);
  }
];

async.waterfall(bloodyTrail, function(error, results) {
  if (error) {
    return console.log('Async error:', error);
  } else {
    return console.log('Digestion results:\n', results);
  }
});

//# sourceMappingURL=index.js.map
